import test from 'node:test';import assert from 'node:assert/strict';import {parseCSV,guessMapping,importRows,deduplicate,interpretProgress,escapeHTML,calculatedProgress} from '../web/core.js';
test('CLZ CSV handles BOM, quoted commas, escaped quotes, CRLF and multiline cells',()=>{const csv=parseCSV('\uFEFFTitle,Platform,Genre\r\n"Game, Deluxe",PS5,"Action\nRPG"\r\n"A ""Great"" Game",Switch,Adventure\r\n');assert.equal(csv.rows.length,2);assert.equal(csv.rows[0][0],'Game, Deluxe');assert.equal(csv.rows[0][2],'Action\nRPG');assert.equal(csv.rows[1][0],'A "Great" Game');assert.throws(()=>parseCSV('Title\n"unterminated'),/Unclosed/)});
test('mapping imports wishlist and completed owned games without duplicate loss across platforms',()=>{const csv=parseCSV('Title,Console,Collection Status,Status\nZelda,Switch,Wishlist,\nZelda,PS5,Owned,Completed');const imported=importRows(csv,guessMapping(csv.headers));assert.equal(imported[0].collection,'wishlist');assert.equal(imported[1].percent,100);const r=deduplicate([imported[0]],imported);assert.equal(r.added.length,1);assert.equal(r.skipped,1)});
test('unknown chapter requires clarification and never invents a percentage',()=>{assert.equal(interpretProgress('I just finished chapter 8').confirmed,false);assert.equal(interpretProgress('I just started chapter 8').percent,undefined);assert.equal(interpretProgress('I finished chapter 8',[{chapter:8,label:'Chapter 8',percent:42}]).percent,42);assert.equal(interpretProgress('I finished the main story').percent,100)});
test('imported HTML is escaped',()=>assert.equal(escapeHTML('<img onerror="bad">'),'&lt;img onerror=&quot;bad&quot;&gt;'));

test('incomplete or negated milestones never count as complete',()=>{assert.equal(interpretProgress('I have not finished the main story').confirmed,false);assert.equal(interpretProgress('I almost finished chapter 8',[{chapter:8,label:'Chapter 8',percent:42}]).confirmed,false);assert.equal(interpretProgress('I started The Rescue',[{chapter:1,label:'The Rescue',percent:5}]).confirmed,false)});

test('unresolved percentages cannot become zero or be saved as guessed numbers',()=>{assert.equal(calculatedProgress({percent:null}),null);assert.equal(calculatedProgress({}),null);assert.equal(calculatedProgress({percent:NaN}),null);assert.equal(calculatedProgress({percent:101}),null);assert.equal(calculatedProgress({percent:42.4}),42);assert.equal(calculatedProgress({percent:100}),100);assert.ok(!interpretProgress('I finished chapter 8').question.includes('percentage'));});
